"""
Run this once with: python build_notebooks.py
It generates:
  - GPU_Vegan_Alternatives_DB_Generator.ipynb
  - GPU_Indian_Budget_Vegan_Recipe_Generator.ipynb

Both notebooks include a final cell that uploads the generated data
to MongoDB Atlas (using your existing MONGO_URI from .env).
"""
import json

# â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
#  NOTEBOOK 1: Vegan Alternatives Database Generator (CPU ok)
# â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
nb1_cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# ðŸŒ¿ Vegan Alternatives Database Generator\n",
            "\n",
            "Run on **Google Colab (CPU is fine â€” pure NumPy math)**.\n",
            "\n",
            "This notebook:\n",
            "1. Clones your repo â†’ gets `vegan_engine.py` + `chemical_features.json`\n",
            "2. Runs the Composite Scoring Engine on every non-veg ingredient vs all vegan candidates\n",
            "3. Saves **top-5 vegan alternatives** per ingredient â†’ `vegan_alternatives_db.json` + `.csv`",
        ],
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# â”€â”€ Cell 1: Clone repo â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€\n",
            "!git clone https://github.com/dn74iiit/ratatouille-app.git\n",
            "%cd ratatouille-app\n",
            "!pip install numpy -q\n",
        ],
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# â”€â”€ Cell 2: Engine functions (mirrors vegan_engine.py exactly) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€\n",
            "import json, numpy as np, csv\n",
            "from datetime import datetime\n",
            "\n",
            "DB_PATH = 'chemical_features.json'\n",
            "\n",
            "def load_features():\n",
            "    with open(DB_PATH) as f: return json.load(f)\n",
            "\n",
            "def jaccard_similarity(a, b):\n",
            "    if not a or not b: return 0.0\n",
            "    i = len(a & b); u = len(a | b)\n",
            "    return i / u if u > 0 else 0.0\n",
            "\n",
            "def texture_similarity(va, vb):\n",
            "    if not va or not vb: return 0.5\n",
            "    dist = float(np.linalg.norm(np.array(va, float) - np.array(vb, float)))\n",
            "    return 1.0 - dist / 9.798  # max Euclidean dist for 6D [1-5] space\n",
            "\n",
            "def functional_overlap(ra, rb): return 1.0 if ra == rb else 0.0\n",
            "\n",
            "def composite_score(od, cd, a=0.3, b=0.4, g=0.3):\n",
            "    fl = jaccard_similarity(set(od.get('flavor_molecules',[])), set(cd.get('flavor_molecules',[])))\n",
            "    tx = texture_similarity(od.get('texture',[]), cd.get('texture',[]))\n",
            "    fn = functional_overlap(od.get('role',''), cd.get('role',''))\n",
            "    total = round(a*fl + b*tx + g*fn, 4)\n",
            "    return total, {'flavor_similarity': round(fl,4), 'texture_similarity': round(tx,4), 'functional_fit': round(fn,4)}\n",
            "\n",
            "def spice_bridge(orig_mols, sub_mols, feats, k=3):\n",
            "    gap = set(orig_mols) - set(sub_mols)\n",
            "    if not gap: return []\n",
            "    res = []\n",
            "    for nm, d in feats.items():\n",
            "        if d.get('is_spice') and d.get('is_vegan'):\n",
            "            sm = set(d.get('flavor_molecules',[]))\n",
            "            sc = len(sm & gap) / len(gap)\n",
            "            if sc > 0: res.append({'spice': nm, 'fills_gap_ratio': round(sc,3)})\n",
            "    res.sort(key=lambda x: x['fills_gap_ratio'], reverse=True)\n",
            "    return res[:k]\n",
            "\n",
            "def culinary_note(sub_name, od, cd):\n",
            "    dw = cd.get('macros',{}).get('water',0) - od.get('macros',{}).get('water',0)\n",
            "    ot = od.get('texture',[0]*6); st = cd.get('texture',[0]*6)\n",
            "    notes = []\n",
            "    if dw < -0.1: notes.append('Press ' + sub_name + ' 15 min to remove excess moisture.')\n",
            "    elif dw > 0.2: notes.append('Soak ' + sub_name + ' in hot water 15 min and squeeze dry.')\n",
            "    if sub_name == 'jackfruit': notes.append('Shred with two forks after simmering.')\n",
            "    elif sub_name == 'tofu' and len(ot)>2 and len(st)>2 and (ot[2]-st[2]>1 or ot[1]-st[1]>1):\n",
            "        notes.append('Freeze/thaw then pan-sear until golden for better texture.')\n",
            "    elif sub_name == 'soya chunks' and len(ot)>2 and len(st)>2 and ot[2]-st[2]>2:\n",
            "        notes.append('Soak in boiling water 15 min, squeeze dry, pan-fry before adding to sauce.')\n",
            "    elif sub_name == 'king oyster mushroom':\n",
            "        notes.append('Score stalks in cross-hatch pattern, saute in oil to mimic shrimp bite.')\n",
            "    if not notes: notes.append('Use as direct replacement with standard cooking method.')\n",
            "    return ' '.join(notes)\n",
            "\n",
            "print('Engine ready.')\n",
        ],
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# â”€â”€ Cell 3: Score every non-veg ingredient against all vegan candidates â”€â”€â”€â”€â”€â”€â”€â”€â”€\n",
            "TOP_K = 5\n",
            "feats = load_features()\n",
            "print('Loaded ' + str(len(feats)) + ' ingredients')\n",
            "\n",
            "non_veg  = {n: d for n,d in feats.items() if not d.get('is_vegan',True) and not d.get('is_spice',False)}\n",
            "veg_pool = [(n,d) for n,d in feats.items()  if d.get('is_vegan',False)  and not d.get('is_spice',False)]\n",
            "print('Non-veg: ' + str(len(non_veg)) + '  |  Vegan pool: ' + str(len(veg_pool)))\n",
            "\n",
            "vegan_db = {}\n",
            "for orig, od in non_veg.items():\n",
            "    scored = []\n",
            "    for cand, cd in veg_pool:\n",
            "        sc, bk = composite_score(od, cd)\n",
            "        sb = spice_bridge(od.get('flavor_molecules',[]), cd.get('flavor_molecules',[]), feats)\n",
            "        df = round(float(od.get('macros',{}).get('fat',0)   - cd.get('macros',{}).get('fat',0)),   3)\n",
            "        dw = round(float(cd.get('macros',{}).get('water',0) - od.get('macros',{}).get('water',0)), 3)\n",
            "        scored.append({'substitute': cand, 'composite_score': sc, 'score_breakdown': bk,\n",
            "                       'chemical_delta': {'lipid_deficit': df, 'moisture_excess': dw},\n",
            "                       'spice_bridge': sb, 'culinary_notes': culinary_note(cand, od, cd)})\n",
            "    scored.sort(key=lambda x: x['composite_score'], reverse=True)\n",
            "    for r, item in enumerate(scored[:TOP_K], 1): item['rank'] = r\n",
            "    vegan_db[orig] = {'original_role': od.get('role','unknown'), 'alternatives': scored[:TOP_K]}\n",
            "    print('  ' + orig.ljust(22) + ' -> ' + scored[0]['substitute'] + ' (score=' + str(scored[0]['composite_score']) + ')')\n",
            "\n",
            "print('Done. Processed ' + str(len(vegan_db)) + ' ingredients.')\n",
        ],
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# â”€â”€ Cell 4: Save JSON â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€\n",
            "out = {'_meta': {'generated_at': datetime.now().isoformat(),\n",
            "                 'scoring_weights': {'alpha_flavor': 0.3, 'beta_texture': 0.4, 'gamma_role': 0.3},\n",
            "                 'top_k': TOP_K, 'total_non_veg': len(vegan_db)},\n",
            "       'alternatives': vegan_db}\n",
            "with open('vegan_alternatives_db.json','w',encoding='utf-8') as f:\n",
            "    json.dump(out, f, indent=2, ensure_ascii=False)\n",
            "print('Saved vegan_alternatives_db.json')\n",
        ],
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# â”€â”€ Cell 5: Save CSV + download both files â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€\n",
            "rows = []\n",
            "for orig, entry in vegan_db.items():\n",
            "    for alt in entry['alternatives']:\n",
            "        rows.append({'original_ingredient': orig, 'original_role': entry['original_role'],\n",
            "                     'rank': alt['rank'], 'vegan_substitute': alt['substitute'],\n",
            "                     'composite_score': alt['composite_score'],\n",
            "                     'flavor_similarity': alt['score_breakdown']['flavor_similarity'],\n",
            "                     'texture_similarity': alt['score_breakdown']['texture_similarity'],\n",
            "                     'functional_fit': alt['score_breakdown']['functional_fit'],\n",
            "                     'lipid_deficit': alt['chemical_delta']['lipid_deficit'],\n",
            "                     'moisture_excess': alt['chemical_delta']['moisture_excess'],\n",
            "                     'spice_bridge': ', '.join(s['spice'] for s in alt['spice_bridge']),\n",
            "                     'culinary_notes': alt['culinary_notes']})\n",
            "with open('vegan_alternatives_db.csv','w',newline='',encoding='utf-8') as f:\n",
            "    w = csv.DictWriter(f, fieldnames=rows[0].keys()); w.writeheader(); w.writerows(rows)\n",
            "print('Saved vegan_alternatives_db.csv (' + str(len(rows)) + ' rows)')\n",
            "from google.colab import files\n",
            "files.download('vegan_alternatives_db.json')\n",
            "files.download('vegan_alternatives_db.csv')\n",
        ],
    },
    # â”€â”€ MongoDB Upload Cell â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# â”€â”€ Cell 6: Upload to MongoDB Atlas (ratatouille.vegan_alternatives) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€\n",
            "# Make sure you add MONGO_URI to your Colab Secrets (the Key icon on the left).\n",
            "!pip install 'pymongo[srv]' -q\n",
            "from google.colab import userdata\n",
            "from pymongo import MongoClient, UpdateOne\n",
            "from datetime import datetime, timezone\n",
            "MONGO_URI = userdata.get('MONGO_URI')\n",
            "client = MongoClient(MONGO_URI)\n",
            "col = client['ratatouille']['vegan_alternatives']\n",
            "ops = []\n",
            "for ingredient_name, entry in vegan_db.items():\n",
            "    doc = {\n",
            "        '_id': ingredient_name,\n",
            "        'original_role': entry['original_role'],\n",
            "        'alternatives': entry['alternatives'],\n",
            "        'updated_at': datetime.now(timezone.utc)\n",
            "    }\n",
            "    ops.append(UpdateOne({'_id': ingredient_name}, {'$set': doc}, upsert=True))\n",
            "result = col.bulk_write(ops)\n",
            "print('MongoDB upload done. Upserted:', result.upserted_count, '| Modified:', result.modified_count)\n",
            "print('Collection: ratatouille.vegan_alternatives |', col.count_documents({}), 'total docs')\n",
            "client.close()\n",
        ],
    },
]

nb1 = {
    "cells": nb1_cells,
    "metadata": {
        "accelerator": "None",
        "colab": {"provenance": []},
        "kernelspec": {"display_name": "Python 3", "name": "python3"},
        "language_info": {"name": "python", "version": "3.10.0"},
    },
    "nbformat": 4,
    "nbformat_minor": 4,
}

with open("GPU_Vegan_Alternatives_DB_Generator.ipynb", "w", encoding="utf-8") as f:
    json.dump(nb1, f, indent=2, ensure_ascii=False)
print("Written GPU_Vegan_Alternatives_DB_Generator.ipynb")


# â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
#  NOTEBOOK 2: Indian Budget Vegan Recipe Generator (GPU T4)
# â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

# â”€â”€ Post-processing: the EXACT hallucination-cutting logic from api.py lines 640-666 â”€â”€
POST_PROCESS_CODE = """\
def clean_recipe_output(ai_text: str) -> str:
    \"\"\"
    Exact hallucination-cutting logic from api.py (lines 640-666).
    Applies in order:
      1. Cut at <|eot_id|>  (model's own stop token)
      2. If multiple '### TITLE:' blocks, keep only the first recipe
      3. Strip trailing conversational rambling / notes
      4. If extra '### ' sections appear inside DIRECTIONS, cut there
    \"\"\"
    # 1. Cut at the model's stop token (most reliable signal)
    stop_tokens = ['<|eot_id|>', '<|end_of_text|>', '<|begin_of_text|>', '\n### INGREDIENTS:']
    for t in stop_tokens:
        if t in ai_text:
            ai_text = ai_text.split(t)[0].strip()

    # 2. If the model looped back and added another TITLE block, keep only the first recipe
    if '### TITLE:\\n' in ai_text:
        ai_text = ai_text.split('### TITLE:\\n')[1].strip()

    # 3. Cut trailing rambling signatures (from api.py cut_phrases list)
    cut_phrases = [
        '\\nEnjoy!', '\\nServe hot', '\\nBon Apetit', '\\nChef\\'s Note:',
        '\\nVariations:', '\\nServing suggestion:', '\\nNote:'
    ]
    for phrase in cut_phrases:
        if phrase in ai_text:
            ai_text = ai_text.split(phrase)[0].strip()

    # 4. If another '### ' header appears inside DIRECTIONS, cut it off
    #    (the only valid '###' in output should be '### DIRECTIONS:')
    if '### DIRECTIONS:\\n' in ai_text:
        parts = ai_text.split('### DIRECTIONS:\\n')
        title_part = parts[0]
        directions_part = parts[1]
        if '\\n### ' in directions_part:
            directions_part = directions_part.split('\\n### ')[0]
        ai_text = (title_part + '### DIRECTIONS:\\n' + directions_part).strip()

    return ai_text
"""

# â”€â”€ Indian-budget recipe templates â”€â”€
TEMPLATES_CODE = """\
# â”€â”€â”€ Indian Budget Vegan Recipe Templates â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
# Inspired by everyday Indian staple-based cooking under INR 150/serving
# Each template specifies which non-veg it replaces, vegan sub, and base spices.

INDIAN_TEMPLATES = [
    # POULTRY substitutions
    {"name": "Soya Chunks Biryani",       "original": "chicken",      "sub": "soya chunks",
     "style": "Rice_Dish", "budget_inr": 120,
     "ingredients": ["soya chunks","basmati rice","onion","tomato","ginger","garlic","biryani masala","oil","mint","green chili"]},
    {"name": "Soya Chunks Curry",          "original": "chicken",      "sub": "soya chunks",
     "style": "Curry", "budget_inr": 100,
     "ingredients": ["soya chunks","onion","tomato","garlic","ginger","cumin","turmeric","red chili powder","garam masala","oil"]},
    {"name": "Jackfruit Kadai",            "original": "chicken",      "sub": "jackfruit",
     "style": "Dry_Sabzi", "budget_inr": 90,
     "ingredients": ["raw jackfruit","capsicum","onion","tomato","kadai masala","ginger","garlic","oil","cumin seeds"]},
    {"name": "Tofu Butter Masala",         "original": "chicken",      "sub": "tofu",
     "style": "Curry", "budget_inr": 130,
     "ingredients": ["tofu","tomato puree","onion","cashew","cream","butter","garam masala","kashmiri chili","sugar"]},
    {"name": "Tempeh Stir Fry",            "original": "chicken",      "sub": "tempeh",
     "style": "Dry_Sabzi", "budget_inr": 110,
     "ingredients": ["tempeh","cabbage","carrot","soy sauce","garlic","ginger","sesame oil","green onion"]},
    # RED MEAT substitutions
    {"name": "Rajma Keema",                "original": "mutton",       "sub": "kidney beans",
     "style": "Curry", "budget_inr": 80,
     "ingredients": ["kidney beans","onion","tomato","garlic","ginger","cumin","coriander","red chili powder","garam masala","oil"]},
    {"name": "Lentil Kofta Curry",         "original": "mutton",       "sub": "red lentils",
     "style": "Curry", "budget_inr": 70,
     "ingredients": ["red lentils","onion","tomato","garlic","ginger","cumin seeds","turmeric","coriander powder","oil"]},
    {"name": "Jackfruit Vindaloo",         "original": "pork",         "sub": "jackfruit",
     "style": "Curry", "budget_inr": 95,
     "ingredients": ["raw jackfruit","vinegar","garlic","dried red chili","cumin","mustard seeds","tamarind","oil","onion"]},
    {"name": "Soya Keema Matar",           "original": "minced meat",  "sub": "soya granules",
     "style": "Curry", "budget_inr": 85,
     "ingredients": ["soya granules","green peas","onion","tomato","ginger","garlic","cumin","garam masala","oil","salt"]},
    {"name": "Tempeh Rogan Josh",          "original": "beef",         "sub": "tempeh",
     "style": "Curry", "budget_inr": 115,
     "ingredients": ["tempeh","yogurt","onion","fennel seeds","kashmiri chili","ginger powder","cinnamon","cardamom","oil"]},
    # SEAFOOD substitutions
    {"name": "Mushroom Masala Curry",      "original": "fish",         "sub": "mushroom",
     "style": "Curry", "budget_inr": 100,
     "ingredients": ["button mushroom","mustard seeds","turmeric","green chili","coconut milk","onion","tomato","curry leaves","oil"]},
    {"name": "Oyster Mushroom Butter Garlic", "original": "shrimp",    "sub": "king oyster mushroom",
     "style": "Dry_Sabzi", "budget_inr": 120,
     "ingredients": ["king oyster mushroom","vegan butter","garlic","lemon juice","parsley","black pepper","salt"]},
    {"name": "Banana Blossom Malabar Curry",  "original": "fish",         "sub": "banana blossom",
     "style": "Curry", "budget_inr": 80,
     "ingredients": ["banana blossom","coconut milk","mustard seeds","turmeric","tamarind","onion","tomato","curry leaves"]},
    {"name": "Chickpea Coconut Masala",       "original": "crab",         "sub": "chickpeas",
     "style": "Curry", "budget_inr": 75,
     "ingredients": ["chickpeas","coconut","dried red chili","tamarind","onion","tomato","coriander seeds","mustard seeds","oil"]},
    # DAIRY substitutions
    {"name": "Tofu Palak",                 "original": "paneer",       "sub": "tofu",
     "style": "Curry", "budget_inr": 100,
     "ingredients": ["tofu","spinach","onion","garlic","ginger","cumin","cream","garam masala","oil","nutmeg"]},
    {"name": "Tofu Matar",                 "original": "paneer",       "sub": "tofu",
     "style": "Curry", "budget_inr": 90,
     "ingredients": ["tofu","green peas","onion","tomato","ginger","garlic","cumin seeds","turmeric","garam masala","oil"]},
    {"name": "Soya Bhurji",                "original": "egg",          "sub": "tofu scramble",
     "style": "Dry_Sabzi", "budget_inr": 60,
     "ingredients": ["tofu","onion","green chili","tomato","turmeric","cumin seeds","coriander leaves","oil","salt"]},
    {"name": "Chickpea Omelette",          "original": "egg",          "sub": "chickpea flour",
     "style": "Dry_Sabzi", "budget_inr": 50,
     "ingredients": ["chickpea flour","onion","green chili","tomato","turmeric","cumin","oil","salt","water"]},
    # DAL & STAPLE dishes (vegan by nature, budget-focused)
    {"name": "Dal Tadka",                  "original": None,           "sub": "toor dal",
     "style": "Soup", "budget_inr": 60,
     "ingredients": ["toor dal","onion","tomato","garlic","ginger","cumin seeds","turmeric","ghee vegan","red chili","asafoetida"]},
    {"name": "Chana Masala",               "original": None,           "sub": "chickpeas",
     "style": "Curry", "budget_inr": 70,
     "ingredients": ["chickpeas","onion","tomato","garlic","ginger","cumin","coriander","amchur","garam masala","oil"]},
    {"name": "Rajma Chawal",               "original": None,           "sub": "kidney beans",
     "style": "Rice_Dish", "budget_inr": 80,
     "ingredients": ["kidney beans","basmati rice","onion","tomato","garlic","ginger","cumin","garam masala","bay leaf","oil"]},
    {"name": "Aloo Gobi Sabzi",            "original": None,           "sub": "potato + cauliflower",
     "style": "Dry_Sabzi", "budget_inr": 50,
     "ingredients": ["potato","cauliflower","onion","tomato","turmeric","cumin seeds","coriander powder","green chili","oil"]},
    {"name": "Masoor Dal",                 "original": None,           "sub": "red lentils",
     "style": "Soup", "budget_inr": 55,
     "ingredients": ["red lentils","onion","tomato","garlic","turmeric","cumin seeds","red chili","oil","salt","lemon"]},
    {"name": "Baingan Bharta",             "original": None,           "sub": "eggplant",
     "style": "Dry_Sabzi", "budget_inr": 65,
     "ingredients": ["eggplant","onion","tomato","garlic","green chili","cumin seeds","turmeric","coriander leaves","oil"]},
    {"name": "Mixed Veg Sabzi",            "original": None,           "sub": "seasonal vegetables",
     "style": "Dry_Sabzi", "budget_inr": 60,
     "ingredients": ["carrot","beans","potato","peas","onion","tomato","cumin seeds","turmeric","garam masala","oil"]},
    # NEW ADDITIONS (Fish, Pork, Crab, Duck, etc.)
    {"name": "Banana Blossom Malabar Curry",  "original": "fish",         "sub": "banana blossom",
     "style": "Curry", "budget_inr": 85,
     "ingredients": ["banana blossom","mustard seeds","turmeric","coconut milk","tamarind","onion","tomato","green chili","oil"]},
    {"name": "Jackfruit Vindaloo",         "original": "pork",         "sub": "jackfruit",
     "style": "Curry", "budget_inr": 95,
     "ingredients": ["raw jackfruit","vinegar","garlic","dried red chili","cumin seeds","mustard seeds","onion","oil"]},
    {"name": "Chickpea Coconut Masala",       "original": "crab",         "sub": "chickpeas",
     "style": "Curry", "budget_inr": 75,
     "ingredients": ["chickpeas","coconut","fennel seeds","dried red chili","onion","tomato","garlic","ginger","oil"]},
    {"name": "Mushroom Pepper Roast",        "original": "duck",         "sub": "king oyster mushroom",
     "style": "Dry_Sabzi", "budget_inr": 120,
     "ingredients": ["king oyster mushroom","onion","black pepper","fennel seeds","garlic","ginger","curry leaves","oil"]},
    {"name": "Soya Chunks Chili Stir Fry", "original": "squid",     "sub": "soya chunks",
     "style": "Dry_Sabzi", "budget_inr": 90,
     "ingredients": ["soya chunks","capsicum","onion","black pepper","soy sauce","garlic","ginger","oil"]},
    {"name": "Tofu Tikka Masala",          "original": "turkey",       "sub": "tofu",
     "style": "Dry_Sabzi", "budget_inr": 110,
     "ingredients": ["tofu","yogurt vegan","tikka masala","kashmiri chili","lemon juice","garlic","ginger","oil"]},
    {"name": "Smoky Tempeh Fry",           "original": "bacon",        "sub": "tempeh",
     "style": "Dry_Sabzi", "budget_inr": 130,
     "ingredients": ["tempeh","soy sauce","maple syrup","smoked paprika","garlic powder","oil"]},
    {"name": "Soya Granules Masala Curry", "original": "sausage",     "sub": "soya granules",
     "style": "Curry", "budget_inr": 85,
     "ingredients": ["soya granules","onion","tomato","garlic","ginger","cumin","garam masala","oil"]}
]

import random
import itertools

proteins = ['tofu', 'soya chunks', 'chickpeas', 'kidney beans', 'red lentils', 'tempeh', 'soya granules']
veggies = ['potato', 'cauliflower', 'spinach', 'eggplant', 'green peas', 'capsicum', 'mushroom', 'bottle gourd', 'okra', 'cabbage']
bases = ['onion', 'tomato', 'garlic', 'ginger', 'coconut milk', 'tamarind']
styles = ['Curry', 'Dry_Sabzi', 'Soup', 'Rice_Dish']

combos = []
for p in proteins:
    for v in veggies:
        for style in styles:
            # pick random bases
            num_bases = random.randint(2, 4)
            chosen_bases = random.sample(bases, num_bases)
            combos.append({
                'name': '',
                'original': None,
                'sub': None,
                'style': style,
                'budget_inr': random.randint(50, 140),
                'ingredients': [p, v, 'oil', 'cumin seeds', 'turmeric', 'salt'] + chosen_bases
            })

# We generated thousands. We just need 467 to reach 500 total (33 + 467 = 500)
random.seed(42) # repeatable
random.shuffle(combos)
INDIAN_TEMPLATES.extend(combos[:467])

print('Loaded ' + str(len(INDIAN_TEMPLATES)) + ' Indian budget vegan recipe templates')
"""

nb2_cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# ðŸ‡®ðŸ‡³ GPU Indian Budget Vegan Recipe Generator\n",
            "\n",
            "Run on **Google Colab with T4 GPU** (Runtime â†’ Change runtime type â†’ T4 GPU).\n",
            "\n",
            "Uses model: `nd1490/ratatouille-llama3-3b-v10-non-oven` (your V10 non-oven fine-tune).\n",
            "\n",
            "**Post-processing**: uses the exact hallucination-cutting logic from `api.py` (lines 640â€“666):\n",
            "- Cut at `<|eot_id|>` stop token\n",
            "- Strip duplicate `### TITLE:` blocks\n",
            "- Remove trailing `Enjoy!`, `Chef's Note:` etc.\n",
            "- Clip at unexpected `### ` headers inside DIRECTIONS\n",
            "\n",
            "**Output**: `indian_vegan_recipes_db.csv` â€” ~25 Indian-inspired vegan recipes under â‚¹150/serving",
        ],
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# â”€â”€ Cell 1: Install dependencies â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€\n",
            "!pip install unsloth -q\n",
            "!pip install 'unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git' -q\n",
            "!pip install 'trl==0.24.0' peft accelerate bitsandbytes -q\n",
        ],
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# â”€â”€ Cell 2: Clone repo for vegan_engine logic â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€\n",
            "!git clone https://github.com/dn74iiit/ratatouille-app.git\n",
            "%cd ratatouille-app\n",
        ],
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# â”€â”€ Cell 3: Load V10 non-oven model onto GPU â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€\n",
            "import torch\n",
            "from unsloth import FastLanguageModel\n",
            "\n",
            "MODEL_ID = 'nd1490/ratatouille-llama3-3b-v10-non-oven'\n",
            "\n",
            "print('Loading ' + MODEL_ID + ' on GPU...')\n",
            "model, tokenizer = FastLanguageModel.from_pretrained(\n",
            "    model_name=MODEL_ID,\n",
            "    max_seq_length=1024,\n",
            "    load_in_4bit=True,\n",
            "    dtype=None,          # auto-detect best dtype\n",
            ")\n",
            "FastLanguageModel.for_inference(model)  # enable 2x faster inference\n",
            "print('Model ready on ' + str(torch.cuda.get_device_name(0)))\n",
        ],
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": POST_PROCESS_CODE,
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": TEMPLATES_CODE,
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# â”€â”€ Cell 6: Prompt builder â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€\n",
            "def build_indian_prompt(template: dict) -> str:\n",
            "    ingr_text = '\\n'.join('- ' + i for i in template['ingredients'])\n",
            "    style = template['style']\n",
            "    system_instruction = (\n",
            "        'You are a master chef. Write a highly detailed, appetizing recipe for a ' + style + '.\\n'\n",
            "        'First, provide a creative title. Then, provide step-by-step cooking directions using proper culinary techniques.\\n'\n",
            "        'CRITICAL RULES:\\n'\n",
            "        '1. Ensure all raw ingredients (especially rice, grains, and meats) are explicitly cooked in the instructions.\\n'\n",
            "        '2. Do not change the ingredient quantities provided.\\n'\n",
            "        '3. DO NOT include any \\'Notes\\', \\'Tips\\', or conversational rambling at the end. Stop immediately after the final serving step.'\n",
            "    )\n",
            "    prompt = (\n",
            "        '<|begin_of_text|><|start_header_id|>system<|end_header_id|>\\n\\n'\n",
            "        + system_instruction + '<|eot_id|>'\n",
            "        '<|start_header_id|>user<|end_header_id|>\\n\\n'\n",
            "        '### INGREDIENTS:\\n' + ingr_text + '<|eot_id|>'\n",
            "        '<|start_header_id|>assistant<|end_header_id|>\\n\\n'\n",
            "        '### TITLE:\\n'\n",
            "    )\n",
            "    return prompt\n",
            "\n",
            "# Quick sanity test\n",
            "test_prompt = build_indian_prompt(INDIAN_TEMPLATES[0])\n",
            "print('Sample prompt:')\n",
            "print(test_prompt)\n",
        ],
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# â”€â”€ Cell 7: Generation loop â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€\n",
            "import csv, time\n",
            "\n",
            "OUTPUT_CSV = 'indian_vegan_recipes_db.csv'\n",
            "\n",
            "with open(OUTPUT_CSV, 'w', newline='', encoding='utf-8') as csvfile:\n",
            "    fieldnames = ['dish_name','style','budget_inr','original_non_veg','vegan_substitute',\n",
            "                  'ingredients','generated_recipe','model_version','generation_time_s']\n",
            "    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)\n",
            "    writer.writeheader()\n",
            "\n",
            "    for i, tmpl in enumerate(INDIAN_TEMPLATES):\n",
            "        print('[' + str(i+1) + '/' + str(len(INDIAN_TEMPLATES)) + '] Generating: ' + tmpl['name'] + '...')\n",
            "\n",
            "        prompt = build_indian_prompt(tmpl)\n",
            "        inputs = tokenizer(prompt, return_tensors='pt').to('cuda')\n",
            "\n",
            "        start = time.time()\n",
            "        with torch.no_grad():\n",
            "            out = model.generate(\n",
            "                **inputs,\n",
            "                max_new_tokens=600,\n",
            "                temperature=0.7,\n",
            "                top_p=0.9,\n",
            "                repetition_penalty=1.05,\n",
            "                do_sample=True,\n",
            "                eos_token_id=tokenizer.eos_token_id,\n",
            "                pad_token_id=tokenizer.eos_token_id,\n",
            "            )\n",
            "        elapsed = round(time.time() - start, 1)\n",
            "\n",
            "        # Decode only the newly generated tokens (strip the prompt)\n",
            "        input_len = inputs['input_ids'].shape[1]\n",
            "        raw_text = tokenizer.decode(out[0][input_len:], skip_special_tokens=False)\n",
            "\n",
            "        # Apply the exact hallucination-cutting logic from api.py\n",
            "        clean_text = clean_recipe_output(raw_text)\n",
            "        model_title = clean_text.split('\\n')[0].strip()\n",
            "        final_title = tmpl.get('name') if tmpl.get('name') else model_title\n",
            "\n",
            "        writer.writerow({\n",
            "            'dish_name':         final_title,\n",
            "            'style':             tmpl['style'],\n",
            "            'budget_inr':        tmpl['budget_inr'],\n",
            "            'original_non_veg':  tmpl.get('original') or 'vegan',\n",
            "            'vegan_substitute':  tmpl['sub'],\n",
            "            'ingredients':       ', '.join(tmpl['ingredients']),\n",
            "            'generated_recipe':  clean_text,\n",
            "            'model_version':     'nd1490/ratatouille-llama3-3b-v10-non-oven',\n",
            "            'generation_time_s': elapsed,\n",
            "        })\n",
            "        csvfile.flush()\n",
            "        print('   Done in ' + str(elapsed) + 's | output len: ' + str(len(clean_text)) + ' chars')\n",
            "        print('   Preview: ' + clean_text[:120].replace('\\n', ' ') + '...')\n",
            "        print()\n",
            "\n",
            "print('All ' + str(len(INDIAN_TEMPLATES)) + ' recipes generated and saved to ' + OUTPUT_CSV)\n",
        ],
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# â”€â”€ Cell 8: Download the CSV â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€\n",
            "from google.colab import files\n",
            "files.download(OUTPUT_CSV)\n",
            "print('Download triggered for ' + OUTPUT_CSV)\n",
        ],
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# â”€â”€ Cell 9 (Optional): Quick quality sanity check â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€\n",
            "import pandas as pd\n",
            "df = pd.read_csv(OUTPUT_CSV)\n",
            "print('Total recipes:', len(df))\n",
            "print('Avg generation time:', round(df['generation_time_s'].mean(), 1), 'sec')\n",
            "print('Avg recipe length (chars):', round(df['generated_recipe'].str.len().mean(), 0))\n",
            "\n",
            "# Check % of recipes that contain Indian spice markers\n",
            "indian_spices = ['cumin', 'turmeric', 'garam masala', 'coriander', 'mustard']\n",
            "def has_indian_spice(text):\n",
            "    t = text.lower()\n",
            "    return any(sp in t for sp in indian_spices)\n",
            "indian_ratio = df['generated_recipe'].apply(has_indian_spice).mean()\n",
            "print('% with Indian spice profile: ' + str(round(indian_ratio*100, 1)) + '%')\n",
            "\n",
            "# Show first recipe as sample\n",
            "print('\\n' + '='*60)\n",
            "print('SAMPLE RECIPE (first row):')\n",
            "print(df.iloc[0]['dish_name'])\n",
            "print(df.iloc[0]['generated_recipe'][:800])\n",
        ],
    },
    # â”€â”€ MongoDB Upload Cell â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# â”€â”€ Cell 10: Upload generated recipes to MongoDB Atlas (ratatouille.indian_recipes) â”€\n",
            "# Make sure you add MONGO_URI to your Colab Secrets (the Key icon on the left).\n",
            "!pip install 'pymongo[srv]' -q\n",
            "import csv\n",
            "from google.colab import userdata\n",
            "from pymongo import MongoClient\n",
            "from datetime import datetime, timezone\n",
            "MONGO_URI = userdata.get('MONGO_URI')\n",
            "client = MongoClient(MONGO_URI)\n",
            "col = client['ratatouille']['indian_recipes']\n",
            "docs = []\n",
            "with open(OUTPUT_CSV, 'r', encoding='utf-8') as f:\n",
            "    reader = csv.DictReader(f)\n",
            "    for row in reader:\n",
            "        docs.append({\n",
            "            'dish_name':        row['dish_name'],\n",
            "            'style':            row['style'],\n",
            "            'budget_inr':       int(row['budget_inr']),\n",
            "            'original_non_veg': row['original_non_veg'],\n",
            "            'vegan_substitute':  row['vegan_substitute'],\n",
            "            'ingredients_list':  [i.strip() for i in row['ingredients'].split(',')],\n",
            "            'generated_recipe':  row['generated_recipe'],\n",
            "            'model_version':     row['model_version'],\n",
            "            'generation_time_s': float(row['generation_time_s']),\n",
            "            'created_at':        datetime.now(timezone.utc)\n",
            "        })\n",
            "if docs:\n",
            "    result = col.insert_many(docs)\n",
            "    print('MongoDB upload done. Inserted', len(result.inserted_ids), 'recipes.')\n",
            "    print('Collection: ratatouille.indian_recipes |', col.count_documents({}), 'total docs')\n",
            "else:\n",
            "    print('No recipes to upload.')\n",
            "client.close()\n",
        ],
    },
]

nb2 = {
    "cells": nb2_cells,
    "metadata": {
        "accelerator": "GPU",
        "colab": {"provenance": []},
        "kernelspec": {"display_name": "Python 3", "name": "python3"},
        "language_info": {"name": "python", "version": "3.10.0"},
    },
    "nbformat": 4,
    "nbformat_minor": 4,
}

with open("GPU_Indian_Budget_Vegan_Recipe_Generator.ipynb", "w", encoding="utf-8") as f:
    json.dump(nb2, f, indent=2, ensure_ascii=False)
print("Written GPU_Indian_Budget_Vegan_Recipe_Generator.ipynb")

print("\nDone! Both notebooks written.")

# â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
#  NOTEBOOK 3: Open-World Vegan DB Builder
#  Model : Qwen/Qwen3-8B  (4-bit bitsandbytes on T4 GPU)
#  Output: 100% valid JSON via Outlines constrained decoding
# â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
nb3_cells = [
    # â”€â”€ Markdown intro â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# ðŸŒ± Open-World Vegan Substitution Database Builder\n",
            "\n",
            "**Runtime: Google Colab â†’ T4 GPU** | Estimated total time: **~28â€“32 minutes**\n",
            "\n",
            "| Phase | What happens | Est. time |\n",
            "|---|---|---|\n",
            "| 1 | Install deps | 4 min |\n",
            "| 2 | Load Qwen3-8B in 4-bit | 4 min |\n",
            "| 3 | Fetch ingredient vocabulary from bounds_dict | <1 min |\n",
            "| 4 | GPU batch-profile every ingredient via Outlines | ~17 min |\n",
            "| 5 | Self-classify vegan/non-vegan pools | <1 min |\n",
            "| 6 | Open-world NumPy matching math | <1 min |\n",
            "| 7 | Upload match table to MongoDB | ~2 min |\n",
            "\n",
            "> **No preconceived lists.** The model decides `is_vegan` for each ingredient.\n",
            "> Each non-vegan item is scored against the **entire** vegan pool â€” the math picks the winner.\n",
            "> Outlines constrained decoding guarantees **100% valid JSON** on every call.\n",
        ],
    },
    # â”€â”€ Cell 1 : Install dependencies â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Cell 1 â€” Install dependencies\n",
            "!pip install -q transformers accelerate bitsandbytes pymongo dnspython requests tqdm pydantic\\n",
            "# Outlines: constrained JSON decoding (guarantees schema-valid output, no regex needed)\n",
            "# bitsandbytes: 4-bit NF4 quantization for Qwen3-8B on T4 (fits in ~5 GB VRAM)\n",
        ],
    },
    # â”€â”€ Cell 2 : Environment & MongoDB connection â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Cell 2 â€” Environment & MongoDB\n",
            "import os, json, re, io, requests\n",
            "import numpy as np, pandas as pd\n",
            "import pymongo\n",
            "from tqdm import tqdm\n",
            "from google.colab import userdata\n",
            "\n",
            "MONGO_URI  = userdata.get('MONGO_URI')\n",
            "GITHUB_PAT = userdata.get('GITHUB_PAT')\n",
            "if not MONGO_URI:\n",
            "    raise ValueError('Set MONGO_URI in Colab Secrets (key icon on the left).')\n",
            "\n",
            "mongo_client     = pymongo.MongoClient(MONGO_URI)\n",
            "db               = mongo_client.ratatouille\n",
            "features_col     = db.chemical_features    # one doc per ingredient\n",
            "alternatives_col = db.vegan_alternatives   # match table\n",
            "\n",
            "print('âœ… MongoDB connected.')\n",
            "print(f'   chemical_features:  {features_col.count_documents({})} existing docs')\n",
            "print(f'   vegan_alternatives: {alternatives_col.count_documents({})} existing docs')\n",
        ],
    },
    # -- Cell 3 : Vocabulary from bounds_dict only ------------------------------
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Cell 3 -- Ingredient vocabulary from bounds_dict\n",
            "#\n",
            "# bounds_dict keys = the EXACT ingredient names our recipe model writes.\n",
            "# These are the only strings that can ever appear in a generated recipe\n",
            "# that needs a vegan substitute lookup.\n",
            "#\n",
            "# Mandi data is NOT used here -- it is a market pricing dataset whose\n",
            "# commodity labels ('Arhar (Tur)/Red Gram Dal', 'Bajra(Pearl Millet/Cumbu)')\n",
            "# are trade-grade strings that never appear in a recipe.\n",
            "headers = {\n",
            "    'Authorization': f'token {GITHUB_PAT}',\n",
            "    'Accept': 'application/vnd.github.v3.raw'\n",
            "}\n",
            "BOUNDS_URL = 'https://raw.githubusercontent.com/dn74iiit/recipe-data-automation/main/v8_lemmaized_ingredient_bounds.json'\n",
            "\n",
            "r = requests.get(BOUNDS_URL, headers=headers)\n",
            "if r.status_code != 200:\n",
            "    raise RuntimeError(f'Failed to fetch bounds_dict ({r.status_code}). Check GITHUB_PAT secret.')\n",
            "\n",
            "bounds_dict = r.json()\n",
            "full_vocab  = sorted(set(k.strip().lower() for k in bounds_dict.keys()))\n",
            "\n",
            "print(f'Vocabulary: {len(full_vocab)} ingredients from bounds_dict')\n",
            "print('Sample:', full_vocab[:15])\n",
        ],
    },
    # â”€â”€ Cell 4 : Load Qwen3-8B in 4-bit on T4 GPU â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Cell 4 â€” Load Qwen/Qwen3-8B in NF4 4-bit (fits in ~5 GB of T4's 15 GB VRAM)\n",
            "import torch\n",
            "from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig\n",
            "\n",
            "MODEL_ID = 'Qwen/Qwen3-8B'   # Best structured-output model in the 7-9B tier (June 2026)\n",
            "\n",
            "bnb_config = BitsAndBytesConfig(\n",
            "    load_in_4bit=True,\n",
            "    bnb_4bit_quant_type='nf4',\n",
            "    bnb_4bit_compute_dtype=torch.float16,\n",
            "    bnb_4bit_use_double_quant=True,   # saves an extra ~0.4 GB\n",
            ")\n",
            "\n",
            "print('ðŸ“¥ Loading tokenizer...')\n",
            "tokenizer = AutoTokenizer.from_pretrained(MODEL_ID, trust_remote_code=True)\n",
            "\n",
            "print('ðŸ“¥ Loading Qwen3-8B in 4-bit NF4 on GPU...')\n",
            "hf_model = AutoModelForCausalLM.from_pretrained(\n",
            "    MODEL_ID,\n",
            "    device_map='auto',\n",
            "    quantization_config=bnb_config,\n",
            "    trust_remote_code=True,\n",
            ")\n",
            "hf_model.eval()\n",
            "\n",
            "used_vram = torch.cuda.memory_allocated() / 1e9\n",
            "total_vram = torch.cuda.get_device_properties(0).total_memory / 1e9\n",
            "print(f'âœ… Model loaded. VRAM used: {used_vram:.1f} GB / {total_vram:.1f} GB available')\n",
        ],
    },
    # -- Cell 5 : Profile generator — Qwen3 native JSON + Pydantic validation --
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Cell 5 -- Profile generator\n",
            "# Uses Qwen3-8B native JSON instruction following + Pydantic schema validation.\n",
            "# No outlines needed -- Qwen3-8B follows JSON schemas reliably.\n",
            "# Retry up to 3x with temperature sampling as fallback on the rare malformed output.\n",
            "import json, re, torch\n",
            "from pydantic import BaseModel, ValidationError\n",
            "from typing import List, Literal\n",
            "\n",
            "# ── Pydantic schema ──────────────────────────────────────────────────────────\n",
            "class Macros(BaseModel):\n",
            "    fat:     float\n",
            "    protein: float\n",
            "    carb:    float\n",
            "    water:   float\n",
            "\n",
            "class IngredientProfile(BaseModel):\n",
            "    is_vegan:         bool\n",
            "    macros:           Macros\n",
            "    texture:          List[int]   # exactly 6 ints, each 1-5\n",
            "    flavor_molecules: List[str]   # 3-5 volatile compounds\n",
            "    role: Literal[\n",
            "        'bulk_protein', 'fat_source', 'binder',\n",
            "        'creamy_liquid', 'sweetener', 'seasoning', 'veggie'\n",
            "    ]\n",
            "\n",
            "SCHEMA_EXAMPLE = json.dumps({\n",
            "    'is_vegan': False,\n",
            "    'macros': {'fat': 0.20, 'protein': 0.22, 'carb': 0.0, 'water': 0.58},\n",
            "    'texture': [4, 4, 3, 2, 3, 2],\n",
            "    'flavor_molecules': ['methanethiol', 'dimethyl_sulfide', 'pyrazines'],\n",
            "    'role': 'bulk_protein'\n",
            "}, indent=2)\n",
            "\n",
            "def build_prompt(ingredient: str) -> str:\n",
            "    return (\n",
            "        f'<|im_start|>system\\n'\n",
            "        f'You are a food chemistry database. Respond ONLY with a raw JSON object, no markdown.'\n",
            "        f'<|im_end|>\\n'\n",
            "        f'<|im_start|>user\\n'\n",
            "        f'Generate a chemical profile for: \"{ingredient}\"\\n\\n'\n",
            "        f'Rules:\\n'\n",
            "        f'- is_vegan: true only if 100% plant-based\\n'\n",
            "        f'- macros: fat/protein/carb/water as decimals summing to ~1.0\\n'\n",
            "        f'- texture: exactly 6 integers 1-5 [hardness, chewiness, fibrousness, moisture, elasticity, granularity]\\n'\n",
            "        f'- flavor_molecules: 3-5 real volatile compounds (e.g. hexanal, linalool, pyrazines)\\n'\n",
            "        f'- role: one of bulk_protein/fat_source/binder/creamy_liquid/sweetener/seasoning/veggie\\n\\n'\n",
            "        f'Example:\\n{SCHEMA_EXAMPLE}\\n'\n",
            "        f'<|im_end|>\\n'\n",
            "        f'<|im_start|>assistant\\n'\n",
            "    )\n",
            "\n",
            "def extract_and_validate(raw_text: str) -> dict | None:\n",
            "    text = re.sub(r'```json|```', '', raw_text).strip()\n",
            "    m = re.search(r'\\{.*\\}', text, re.DOTALL)\n",
            "    if not m:\n",
            "        return None\n",
            "    try:\n",
            "        profile = IngredientProfile(**json.loads(m.group(0)))\n",
            "        return profile.model_dump()\n",
            "    except (json.JSONDecodeError, ValidationError):\n",
            "        return None\n",
            "\n",
            "def generate_profile(ingredient: str, max_retries: int = 3) -> dict | None:\n",
            "    prompt = build_prompt(ingredient)\n",
            "    inputs = tokenizer([prompt], return_tensors='pt').to('cuda')\n",
            "    for attempt in range(max_retries):\n",
            "        with torch.no_grad():\n",
            "            out = hf_model.generate(\n",
            "                **inputs,\n",
            "                max_new_tokens=200,\n",
            "                do_sample=(attempt > 0),\n",
            "                temperature=0.3 if attempt > 0 else None,\n",
            "                pad_token_id=tokenizer.eos_token_id,\n",
            "            )\n",
            "        text = tokenizer.decode(out[0][inputs.input_ids.shape[1]:], skip_special_tokens=True)\n",
            "        result = extract_and_validate(text)\n",
            "        if result:\n",
            "            return result\n",
            "        print(f'  retry {attempt+1}/{max_retries} for \"{ingredient}\"')\n",
            "    return None\n",
            "\n",
            "# Sanity check\n",
            "test = generate_profile('paneer')\n",
            "print('Test profile (paneer):')\n",
            "print(json.dumps(test, indent=2))\n",
        ],
    },
    # â”€â”€ Cell 6 : Batch-generate profiles (crash-safe, skip cached) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Cell 6 â€” Batch-generate profiles for the entire vocabulary\n",
            "# - Skips ingredients already cached in MongoDB (crash-safe restarts)\n",
            "# - Upserts to MongoDB immediately after each generation\n",
            "already_cached = set(doc['_id'] for doc in features_col.find({}, {'_id': 1}))\n",
            "to_generate    = [ing for ing in full_vocab if ing not in already_cached]\n",
            "\n",
            "print(f'ðŸ“¦ Total vocabulary : {len(full_vocab)}')\n",
            "print(f'âœ… Already cached   : {len(already_cached)}')\n",
            "print(f'ðŸš€ To generate now  : {len(to_generate)}')\n",
            "print(f'â±  Estimated time   : ~{len(to_generate)*2.5/60:.0f} min on T4\\n')\n",
            "\n",
            "failed = []\n",
            "\n",
            "for ingredient in tqdm(to_generate, desc='Profiling'):\n",
            "    profile = generate_profile(ingredient)\n",
            "    if profile:\n",
            "        doc = {'_id': ingredient, 'name': ingredient, **profile}\n",
            "        features_col.update_one({'_id': ingredient}, {'$set': doc}, upsert=True)\n",
            "    else:\n",
            "        failed.append(ingredient)\n",
            "\n",
            "print(f'\\nâœ… Generated & saved : {len(to_generate) - len(failed)}')\n",
            "if failed:\n",
            "    print(f'âŒ Failed            : {len(failed)} â†’ {failed}')\n",
            "print(f'ðŸ“¦ Total in DB now  : {features_col.count_documents({})}')\n",
        ],
    },
    # â”€â”€ Cell 7 : Self-classify vegan / non-vegan pools â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Cell 7 â€” Load full profile pool & self-classify\n",
            "# The model decided is_vegan for each ingredient â€” no human list used.\n",
            "all_profiles   = {doc['_id']: doc for doc in features_col.find({})}\n",
            "vegan_pool     = {k: v for k, v in all_profiles.items() if v.get('is_vegan') is True}\n",
            "non_vegan_pool = {k: v for k, v in all_profiles.items() if v.get('is_vegan') is False}\n",
            "\n",
            "print(f'Total profiled       : {len(all_profiles)}')\n",
            "print(f'Vegan candidate pool : {len(vegan_pool)}')\n",
            "print(f'Non-vegan items      : {len(non_vegan_pool)}')\n",
            "print()\n",
            "print('Sample vegan pool    :', list(vegan_pool.keys())[:10])\n",
            "print('Sample non-vegan     :', list(non_vegan_pool.keys())[:10])\n",
        ],
    },
    # â”€â”€ Cell 8 : Matching math functions â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Cell 8 â€” Matching math (pure NumPy, runs in < 30 seconds for 400+ ingredient pool)\n",
            "\n",
            "def jaccard(a: list, b: list) -> float:\n",
            "    sa, sb = set(a), set(b)\n",
            "    return len(sa & sb) / len(sa | sb) if (sa | sb) else 0.0\n",
            "\n",
            "def texture_sim(va: list, vb: list) -> float:\n",
            "    \"\"\"Normalised 6D Euclidean similarity (1 = identical, 0 = maximally different).\"\"\"\n",
            "    # Pad/trim to 6 dims in case model returned wrong length\n",
            "    va = (va + [3]*6)[:6]\n",
            "    vb = (vb + [3]*6)[:6]\n",
            "    dist = float(np.linalg.norm(np.array(va, float) - np.array(vb, float)))\n",
            "    return max(0.0, 1.0 - dist / 9.798)  # max dist for 6D [1-5] space\n",
            "\n",
            "def composite_score(orig: dict, cand: dict,\n",
            "                    alpha=0.30, beta=0.40, gamma=0.30) -> tuple:\n",
            "    fl = jaccard(orig.get('flavor_molecules', []), cand.get('flavor_molecules', []))\n",
            "    tx = texture_sim(orig.get('texture', [3]*6), cand.get('texture', [3]*6))\n",
            "    fn = 1.0 if orig.get('role') == cand.get('role') else 0.0\n",
            "    score = round(alpha*fl + beta*tx + gamma*fn, 4)\n",
            "    breakdown = {\n",
            "        'flavor_similarity': round(fl, 4),\n",
            "        'texture_similarity': round(tx, 4),\n",
            "        'functional_fit':     round(fn, 4),\n",
            "    }\n",
            "    return score, breakdown\n",
            "\n",
            "def spice_bridge(orig_mols: list, sub_mols: list, top_k=3) -> list:\n",
            "    \"\"\"Find vegan seasonings in the pool that fill the aroma gap.\"\"\"\n",
            "    gap = set(orig_mols) - set(sub_mols)\n",
            "    if not gap:\n",
            "        return []\n",
            "    bridges = []\n",
            "    for name, data in all_profiles.items():\n",
            "        if not data.get('is_vegan'):           continue\n",
            "        if data.get('role') != 'seasoning':    continue\n",
            "        spice_mols = set(data.get('flavor_molecules', []))\n",
            "        covered    = spice_mols & gap\n",
            "        if covered:\n",
            "            bridges.append({\n",
            "                'spice':            name,\n",
            "                'fills_gap_ratio':  round(len(covered) / len(gap), 3),\n",
            "                'supplies':         sorted(covered),\n",
            "            })\n",
            "    bridges.sort(key=lambda x: x['fills_gap_ratio'], reverse=True)\n",
            "    return bridges[:top_k]\n",
            "\n",
            "def delta_blueprint(orig: dict, sub_name: str, sub: dict) -> tuple:\n",
            "    \"\"\"Macro delta â†’ auxiliary additions & prep techniques.\"\"\"\n",
            "    om = orig.get('macros', {})\n",
            "    sm = sub.get('macros',  {})\n",
            "    additions, techniques = [], []\n",
            "    if (om.get('fat', 0) - sm.get('fat', 0)) > 0.10:\n",
            "        additions.append({\n",
            "            'name': 'coconut oil or neutral vegetable oil',\n",
            "            'amount': '1-2 tsp',\n",
            "            'purpose': 'compensates fat deficit in substitution',\n",
            "        })\n",
            "    dw = om.get('water', 0) - sm.get('water', 0)\n",
            "    if dw < -0.10:\n",
            "        techniques.append(f'Press {sub_name} for 15 min to remove excess moisture before cooking.')\n",
            "    elif dw > 0.20:\n",
            "        techniques.append(f'Rehydrate {sub_name} in hot water for 15 min before using.')\n",
            "    return additions, techniques\n",
            "\n",
            "print('âœ… Matching functions ready.')\n",
        ],
    },
    # â”€â”€ Cell 9 : Open-world matching & upload to MongoDB â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# Cell 9 â€” Open-world matching: score every non-vegan vs every vegan in the pool\n",
            "# No pre-conceived candidate list â€” the math alone picks the best substitute.\n",
            "print(f'ðŸ”¥ Matching {len(non_vegan_pool)} non-vegan ingredients'\n",
            "      f' against {len(vegan_pool)} vegan candidates...')\n",
            "\n",
            "match_count = 0\n",
            "\n",
            "for non_veg_name, orig_data in tqdm(non_vegan_pool.items(), desc='Matching'):\n",
            "    scored = []\n",
            "    for veg_name, veg_data in vegan_pool.items():\n",
            "        score, breakdown = composite_score(orig_data, veg_data)\n",
            "        scored.append((veg_name, score, breakdown, veg_data))\n",
            "\n",
            "    if not scored:\n",
            "        continue\n",
            "\n",
            "    scored.sort(key=lambda x: x[1], reverse=True)\n",
            "    best_name, best_score, best_breakdown, best_data = scored[0]\n",
            "\n",
            "    top5 = [\n",
            "        {'substitute': s[0], 'score': s[1], 'breakdown': s[2]}\n",
            "        for s in scored[:5]\n",
            "    ]\n",
            "\n",
            "    additions, techniques = delta_blueprint(orig_data, best_name, best_data)\n",
            "    bridges = spice_bridge(\n",
            "        orig_data.get('flavor_molecules', []),\n",
            "        best_data.get('flavor_molecules', []),\n",
            "    )\n",
            "\n",
            "    match_doc = {\n",
            "        '_id':                    non_veg_name,\n",
            "        'original_ingredient':    non_veg_name,\n",
            "        'best_vegan_substitute':  best_name,\n",
            "        'match_score':            best_score,\n",
            "        'score_breakdown':        best_breakdown,\n",
            "        'top5_alternatives':      top5,\n",
            "        'compensation_blueprint': {\n",
            "            'auxiliary_additions': additions,\n",
            "            'techniques':          techniques,\n",
            "            'spice_bridge':        bridges,\n",
            "        },\n",
            "    }\n",
            "    alternatives_col.update_one(\n",
            "        {'_id': non_veg_name}, {'$set': match_doc}, upsert=True\n",
            "    )\n",
            "    match_count += 1\n",
            "\n",
            "print(f'\\nðŸŽ‰ Done! {match_count} match records written to ratatouille.vegan_alternatives')\n",
            "print(f'   Total docs in collection: {alternatives_col.count_documents({})}')\n",
            "mongo_client.close()\n",
            "print('ðŸ”’ MongoDB connection closed.')\n",
        ],
    },
]

nb3 = {
    "cells": nb3_cells,
    "metadata": {
        "accelerator": "GPU",
        "colab": {"provenance": []},
        "kernelspec": {"display_name": "Python 3", "name": "python3"},
        "language_info": {"name": "python", "version": "3.10.0"},
    },
    "nbformat": 4,
    "nbformat_minor": 4,
}

with open("GPU_Open_World_Vegan_DB_Builder.ipynb", "w", encoding="utf-8") as f:
    json.dump(nb3, f, indent=2, ensure_ascii=False)
print("Written GPU_Open_World_Vegan_DB_Builder.ipynb")

print("\nDone! All 3 notebooks written.")

